# Generated by Django 5.1 on 2024-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certificate_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/pdf'),
        ),
    ]
